"""update_comments_model

Revision ID: aa12de901dfb
Revises: 10ae3071707a
Create Date: 2026-01-10 16:00:07.518765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa12de901dfb'
down_revision: Union[str, None] = '10ae3071707a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_slug', sa.String(length=200), nullable=False))
    op.create_index(op.f('ix_comments_post_slug'), 'comments', ['post_slug'], unique=False)
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'blog_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_post_slug'), table_name='comments')
    op.drop_column('comments', 'post_slug')
    # ### end Alembic commands ###
